pipeline:
  name: cdlab_alsharma
  identifier: cdlab_alsharma
  projectIdentifier: testal
  orgIdentifier: TPMLabs
  tags: {}
  stages:
    - stage:
        name: rolling
        identifier: rolling
        description: Changing for testing
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: sample
          environment:
            environmentRef: dev
            deployToAll: false
            infrastructureDefinitions:
              - identifier: dev_infra
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
              - step:
                  type: HarnessApproval
                  name: HarnessApproval_1
                  identifier: HarnessApproval_1
                  spec:
                    approvalMessage: Please review the following information and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    isAutoRejectEnabled: false
                    approvers:
                      userGroups:
                        - account.test
                      minimumCount: 1
                      disallowPipelineExecutor: false
                    approverInputs: []
                  timeout: 1d
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        delegateSelectors:
          - helm-delegate
  notificationRules:
    - name: Test Notification
      identifier: Test_Notification
      pipelineEvents:
        - type: PipelineFailed
        - type: StageFailed
          forStages:
            - rolling
        - type: StepFailed
      notificationMethod:
        type: Email
        spec:
          userGroups: []
          recipients:
            - al.sharma@harness.io
            - al.sharma@icloud.com
      enabled: true
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1720712151481
        repoName: harness_labs
        build: <+input>
        sparseCheckout: []
