pipeline:
  name: cdlab_alsharma
  identifier: cdlab_alsharma
  projectIdentifier: testal
  orgIdentifier: TPMLabs
  tags: {}
  stages:
    - stage:
        name: rolling
        identifier: rolling
        description: Changing for testing
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: sample
          environment:
            environmentRef: dev
            deployToAll: false
            infrastructureDefinitions:
              - identifier: dev_infra
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        delegateSelectors:
          - helm-delegate
    - stage:
        name: test_approvals
        identifier: test_approvals
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: manual
                  identifier: manual
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - account.test
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
